-- ============================================================================
-- SISTEMA DE FACTURACIÓN HOTELERA (BOLIVIA) - VERSIÓN LEGAL COMPLIANT
-- Incluye: Ley 164, Habeas Data y Estándares de Facturación SIAT
-- ============================================================================

-- 1. TABLA: huésped (Incluye campos de Habeas Data / Derecho al Olvido)
CREATE TABLE IF NOT EXISTS huesped (
    id_huesped BIGSERIAL PRIMARY KEY,
    ci_nit VARCHAR(15) NOT NULL UNIQUE,
    tipo_documento VARCHAR(4) NOT NULL CHECK (tipo_documento IN ('CI', 'NIT')),
    nombre_completo VARCHAR(100) NOT NULL,
    razon_social VARCHAR(100),
    telefono VARCHAR(20),
    direccion VARCHAR(200),
    fecha_registro DATE NOT NULL DEFAULT CURRENT_DATE,
    -- Campos de cumplimiento legal:
    estado_habeas_data VARCHAR(20) DEFAULT 'Activo' CHECK (estado_habeas_data IN ('Activo', 'Anonimizado')),
    fecha_solicitud_baja TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    
    CONSTRAINT chk_ci_formato CHECK (
        (tipo_documento = 'CI' AND ci_nit ~ '^[0-9]{7,10}$') OR -- Ajustado a 10 por CIs nuevos
        (tipo_documento = 'NIT' AND ci_nit ~ '^[0-9]{9,13}$')
    )
);

-- 2. TABLA: consentimiento_datos (Habeas Data - Art. 130 CPE)
CREATE TABLE IF NOT EXISTS consentimiento_datos (
    id_consentimiento BIGSERIAL PRIMARY KEY,
    id_huesped BIGINT NOT NULL REFERENCES huesped(id_huesped) ON DELETE CASCADE,
    fecha_aceptacion TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    version_politica VARCHAR(10) DEFAULT 'v1.0',
    canal VARCHAR(20) DEFAULT 'Recepción', 
    autoriza_tratamiento_datos BOOLEAN DEFAULT TRUE
);

-- 3. TABLA: habitación
CREATE TABLE IF NOT EXISTS habitacion (
    id_habitacion BIGSERIAL PRIMARY KEY,
    numero VARCHAR(10) NOT NULL UNIQUE,
    tipo VARCHAR(30) DEFAULT 'Estándar',
    tarifa_base DECIMAL(10,2) NOT NULL CHECK (tarifa_base > 0),
    estado VARCHAR(15) NOT NULL DEFAULT 'Disponible' CHECK (estado IN ('Disponible', 'Ocupada', 'Mantenimiento')),
    capacidad INT DEFAULT 2,
    piso INT DEFAULT 1,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 4. TABLA: hospedaje
CREATE TABLE IF NOT EXISTS hospedaje (
    id_hospedaje BIGSERIAL PRIMARY KEY,
    id_huesped BIGINT NOT NULL REFERENCES huesped(id_huesped) ON DELETE RESTRICT,
    id_habitacion BIGINT NOT NULL REFERENCES habitacion(id_habitacion) ON DELETE RESTRICT,
    fecha_entrada DATE NOT NULL,
    fecha_salida DATE NOT NULL,
    tarifa_diaria_aplicada DECIMAL(10,2) NOT NULL CHECK (tarifa_diaria_aplicada > 0),
    dias INT NOT NULL CHECK (dias >= 1),
    subtotal DECIMAL(12,2) NOT NULL CHECK (subtotal >= 0),
    estado VARCHAR(15) NOT NULL DEFAULT 'Pendiente' CHECK (estado IN ('Pendiente', 'Finalizado')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),

    CONSTRAINT chk_fechas_hospedaje CHECK (fecha_salida >= fecha_entrada)
);

-- 5. TABLA: factura (Incluye campos SIAT - Impuestos Nacionales)
CREATE TABLE IF NOT EXISTS factura (
    id_factura BIGSERIAL PRIMARY KEY,
    id_hospedaje BIGINT NOT NULL UNIQUE REFERENCES hospedaje(id_hospedaje) ON DELETE RESTRICT,
    numero_factura BIGINT GENERATED BY DEFAULT AS IDENTITY,
    fecha_emision TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    monto_total DECIMAL(12,2) NOT NULL CHECK (monto_total >= 0),
    nit_emisor VARCHAR(15) NOT NULL,
    nombre_emisor VARCHAR(100) NOT NULL,
    -- Campos requeridos por normativa boliviana (SIAT):
    cuf VARCHAR(100), -- Código Único de Factura
    cufd VARCHAR(100), -- Código Único de Facturación Diaria
    codigo_control VARCHAR(50), -- Solo para facturación computarizada antigua
    leyenda_ley_453 TEXT, -- Mensaje obligatorio de defensa al consumidor
    estado VARCHAR(15) NOT NULL DEFAULT 'Emitida' CHECK (estado IN ('Emitida', 'Anulada')),
    motivo_anulacion TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 6. TABLA: logs_auditoria (Ley 164 - Integridad y No Repudio)
CREATE TABLE IF NOT EXISTS logs_auditoria (
    id_log BIGSERIAL PRIMARY KEY,
    tabla_afectada VARCHAR(50) NOT NULL,
    id_registro_afectado BIGINT NOT NULL,
    operacion VARCHAR(10) NOT NULL, -- INSERT, UPDATE, DELETE
    valor_anterior JSONB,
    valor_nuevo JSONB,
    usuario_id UUID, -- Se vincula con auth.users de Supabase
    fecha_evento TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 7. ÍNDICES
CREATE INDEX idx_huesped_ci_nit ON huesped(ci_nit);
CREATE INDEX idx_factura_cuf ON factura(cuf);

-- 8. TRIGGERS Y FUNCIONES

-- A. Actualizar estado de habitación
CREATE OR REPLACE FUNCTION trg_actualizar_estado_habitacion()
RETURNS TRIGGER AS $$
BEGIN
    IF (TG_OP = 'INSERT' AND NEW.estado = 'Pendiente') THEN
        UPDATE habitacion SET estado = 'Ocupada' WHERE id_habitacion = NEW.id_habitacion;
    ELSIF (TG_OP = 'UPDATE' AND NEW.estado = 'Finalizado') THEN
        UPDATE habitacion SET estado = 'Disponible' WHERE id_habitacion = NEW.id_habitacion;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_hospedaje_habitacion_estado
AFTER INSERT OR UPDATE ON hospedaje
FOR EACH ROW EXECUTE FUNCTION trg_actualizar_estado_habitacion();

-- B. Auditoría de Facturas (Ley 164)
CREATE OR REPLACE FUNCTION trg_auditar_factura()
RETURNS TRIGGER AS $$
BEGIN
    IF (TG_OP = 'UPDATE') THEN
        INSERT INTO logs_auditoria(tabla_afectada, id_registro_afectado, operacion, valor_anterior, valor_nuevo)
        VALUES ('factura', OLD.id_factura, 'UPDATE', to_jsonb(OLD), to_jsonb(NEW));
    ELSIF (TG_OP = 'DELETE') THEN
        INSERT INTO logs_auditoria(tabla_afectada, id_registro_afectado, operacion, valor_anterior)
        VALUES ('factura', OLD.id_factura, 'DELETE', to_jsonb(OLD));
    END IF;
    RETURN NULL;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_auditoria_factura
AFTER UPDATE OR DELETE ON factura
FOR EACH ROW EXECUTE FUNCTION trg_auditar_factura();

-- 9. VISTA PARA DERECHO DE ACCESO (Habeas Data)
CREATE OR REPLACE VIEW vista_derecho_acceso AS
SELECT 
    h.id_huesped, h.nombre_completo, h.ci_nit, h.estado_habeas_data,
    f.id_factura, f.monto_total, f.fecha_emision,
    c.fecha_aceptacion AS fecha_consentimiento
FROM huesped h
LEFT JOIN hospedaje hos ON h.id_huesped = hos.id_huesped
LEFT JOIN factura f ON hos.id_hospedaje = f.id_hospedaje
LEFT JOIN consentimiento_datos c ON h.id_huesped = c.id_huesped;
