-- ============================================================================
-- SISTEMA DE FACTURACIÓN HOTELERA (BOLIVIA) - ESQUEMA SUPABASE / POSTGRESQL
-- ============================================================================

-- 1. EXTENSIONES Y LIMPIEZA PREVIA (Opcional)
-- CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 2. TABLA: huésped
CREATE TABLE IF NOT EXISTS huesped (
    id_huesped BIGSERIAL PRIMARY KEY,
    ci_nit VARCHAR(15) NOT NULL UNIQUE,
    tipo_documento VARCHAR(4) NOT NULL CHECK (tipo_documento IN ('CI', 'NIT')),
    nombre_completo VARCHAR(100) NOT NULL,
    razon_social VARCHAR(100),
    telefono VARCHAR(20),
    direccion VARCHAR(200),
    fecha_registro DATE NOT NULL DEFAULT CURRENT_DATE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    
    -- Restricciones de validación de reglas de negocio bolivianas
    CONSTRAINT chk_ci_formato CHECK (
        (tipo_documento = 'CI' AND ci_nit ~ '^[0-9]{7,8}$') OR
        (tipo_documento = 'NIT' AND ci_nit ~ '^[0-9]{9,13}$')
    )
);

-- 3. TABLA: habitación
CREATE TABLE IF NOT EXISTS habitacion (
    id_habitacion BIGSERIAL PRIMARY KEY,
    numero VARCHAR(10) NOT NULL UNIQUE,
    tipo VARCHAR(30) DEFAULT 'Estándar',
    tarifa_base DECIMAL(10,2) NOT NULL CHECK (tarifa_base > 0),
    estado VARCHAR(15) NOT NULL DEFAULT 'Disponible' CHECK (estado IN ('Disponible', 'Ocupada', 'Mantenimiento')),
    capacidad INT DEFAULT 2,
    piso INT DEFAULT 1,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 4. TABLA: hospedaje
CREATE TABLE IF NOT EXISTS hospedaje (
    id_hospedaje BIGSERIAL PRIMARY KEY,
    id_huesped BIGINT NOT NULL REFERENCES huesped(id_huesped) ON DELETE RESTRICT,
    id_habitacion BIGINT NOT NULL REFERENCES habitacion(id_habitacion) ON DELETE RESTRICT,
    fecha_entrada DATE NOT NULL,
    fecha_salida DATE NOT NULL,
    tarifa_diaria_aplicada DECIMAL(10,2) NOT NULL CHECK (tarifa_diaria_aplicada > 0),
    dias INT NOT NULL CHECK (dias >= 1),
    subtotal DECIMAL(12,2) NOT NULL CHECK (subtotal >= 0),
    estado VARCHAR(15) NOT NULL DEFAULT 'Pendiente' CHECK (estado IN ('Pendiente', 'Finalizado')),
    observaciones TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),

    -- Restricción de orden cronológico
    CONSTRAINT chk_fechas_hospedaje CHECK (fecha_salida >= fecha_entrada)
);

-- 5. TABLA: factura
CREATE TABLE IF NOT EXISTS factura (
    id_factura BIGSERIAL PRIMARY KEY,
    id_hospedaje BIGINT NOT NULL UNIQUE REFERENCES hospedaje(id_hospedaje) ON DELETE RESTRICT,
    numero_factura BIGINT GENERATED BY DEFAULT AS IDENTITY,
    fecha_emision TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    monto_total DECIMAL(12,2) NOT NULL CHECK (monto_total >= 0),
    nit_emisor VARCHAR(15) NOT NULL,
    nombre_emisor VARCHAR(100) NOT NULL,
    codigo_control VARCHAR(50),
    autorizacion_nro VARCHAR(50) DEFAULT '45910290001824',
    estado VARCHAR(15) NOT NULL DEFAULT 'Emitida' CHECK (estado IN ('Emitida', 'Anulada')),
    motivo_anulacion TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 6. ÍNDICES DE RENDIMIENTO
CREATE INDEX IF NOT EXISTS idx_huesped_ci_nit ON huesped(ci_nit);
CREATE INDEX IF NOT EXISTS idx_habitacion_estado ON habitacion(estado);
CREATE INDEX IF NOT EXISTS idx_hospedaje_estado ON hospedaje(estado);
CREATE INDEX IF NOT EXISTS idx_factura_fecha ON factura(fecha_emision);

-- 7. TRIGGER PARA ACTUALIZAR ESTADO DE HABITACIÓN A OCUPADA / DISPONIBLE
CREATE OR REPLACE FUNCTION trg_actualizar_estado_habitacion()
RETURNS TRIGGER AS $$
BEGIN
    IF (TG_OP = 'INSERT' AND NEW.estado = 'Pendiente') THEN
        UPDATE habitacion SET estado = 'Ocupada' WHERE id_habitacion = NEW.id_habitacion;
    ELSIF (TG_OP = 'UPDATE' AND NEW.estado = 'Finalizado' AND OLD.estado = 'Pendiente') THEN
        UPDATE habitacion SET estado = 'Disponible' WHERE id_habitacion = NEW.id_habitacion;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trigger_hospedaje_habitacion_estado ON hospedaje;
CREATE TRIGGER trigger_hospedaje_habitacion_estado
AFTER INSERT OR UPDATE ON hospedaje
FOR EACH ROW
EXECUTE FUNCTION trg_actualizar_estado_habitacion();

-- 8. DATOS SEMILLA (Seed Data)
INSERT INTO habitacion (numero, tipo, tarifa_base, estado, capacidad, piso) VALUES
('101', 'Simple Estándar', 180.00, 'Disponible', 1, 1),
('102', 'Doble Twin', 260.00, 'Disponible', 2, 1),
('103', 'Matrimonial King', 320.00, 'Disponible', 2, 1),
('201', 'Suite Ejecutiva', 450.00, 'Disponible', 2, 2),
('202', 'Suite Familiar', 580.00, 'Disponible', 4, 2),
('203', 'Simple Vista Jardín', 210.00, 'Disponible', 1, 2)
ON CONFLICT (numero) DO NOTHING;

INSERT INTO huesped (ci_nit, tipo_documento, nombre_completo, razon_social, telefono, direccion) VALUES
('7382910', 'CI', 'Carlos Eduardo Mendoza Paz', NULL, '77123456', 'Av. Busch #120, La Paz'),
('10293847012', 'NIT', 'Valeria Ramos Gutiérrez', 'CONSTRUCTORA ANDINA S.R.L.', '76543210', 'Calle Calacoto #15, La Paz'),
('6829401', 'CI', 'Fernando Justiniano Suárez', NULL, '68901234', 'Av. San Martín #400, Santa Cruz')
ON CONFLICT (ci_nit) DO NOTHING;
